# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9651273a3a85d6f27880dc4b826abc8767432492f250b2a440eb8b34338120c8e29986c596502aa24d01a13721cb46a800f81789dd1a741329bfdc4698ce978f

test:
  secret_key_base: 4e53cd8d822a30913a98fbcad008082da9f065c9eebba51f5c405cb9ec4b0d103c11726e9528b562f35bb8ccb4f6bf9e8fdbf57db275cd4a5ac646bf9ffca8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
